server:
  # 端口
  port: 8091



spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    #服务器地址

    host: 127.0.0.1
    port: 6379
    timeout: 1000ms
    # 数据库选择
    database: 0
    lettuce:
      pool:
        max-active: 1024
        #最大阻塞等待时间 1ms
        max-wait: 10000ms
      #最大连接数

# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.ybzn.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true

## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.ybzn.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer
  #rabbitMQ配置
  rabbitmq:
    username: guest
    password: guest
    host: 47.115.31.52
    port: 5672
    virtual-host: "/ems"

#fdfs:
#  so-timeout: 2500       # 读取时间
#  connect-timeout: 600   # 连接超时时间
#  thumb-image:           # 缩略图
#    width: 100
#    height: 100
#  tracker-list:          # tracker服务配置地址列表
#    - 192.168.10.100:22122
#upload:
#  base-url: http://192.168.10.100/
#  allow-types:
#    - image/jpeg
#    - image/png
#    - image/bmp
#    - image/gif
